/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FINAL;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ACER
 */
public class Homepage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI frame = (BasicInternalFrameUI)this.getUI();
        frame.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Bhappy = new javax.swing.JButton();
        Bjealous = new javax.swing.JButton();
        Bsad = new javax.swing.JButton();
        Bangry = new javax.swing.JButton();
        Btired = new javax.swing.JButton();
        Bdiss = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jPanel4.setBackground(new java.awt.Color(255, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bhappy.setBackground(new java.awt.Color(255, 153, 255));
        Bhappy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bhappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/happy-face.png"))); // NOI18N
        Bhappy.setBorder(null);
        Bhappy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bhappy.setInheritsPopupMenu(true);
        Bhappy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bhappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhappyActionPerformed(evt);
            }
        });
        jPanel4.add(Bhappy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Bjealous.setBackground(new java.awt.Color(255, 153, 255));
        Bjealous.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bjealous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/jealous.png"))); // NOI18N
        Bjealous.setBorder(null);
        Bjealous.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bjealous.setInheritsPopupMenu(true);
        Bjealous.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bjealous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BjealousActionPerformed(evt);
            }
        });
        jPanel4.add(Bjealous, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        Bsad.setBackground(new java.awt.Color(255, 153, 255));
        Bsad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bsad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/sad.png"))); // NOI18N
        Bsad.setBorder(null);
        Bsad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsadActionPerformed(evt);
            }
        });
        jPanel4.add(Bsad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        Bangry.setBackground(new java.awt.Color(255, 153, 255));
        Bangry.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bangry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/angry.png"))); // NOI18N
        Bangry.setBorder(null);
        Bangry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BangryActionPerformed(evt);
            }
        });
        jPanel4.add(Bangry, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        Btired.setBackground(new java.awt.Color(255, 153, 255));
        Btired.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Btired.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/tired.png"))); // NOI18N
        Btired.setBorder(null);
        Btired.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Btired.setInheritsPopupMenu(true);
        Btired.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Btired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtiredActionPerformed(evt);
            }
        });
        jPanel4.add(Btired, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        Bdiss.setBackground(new java.awt.Color(255, 153, 255));
        Bdiss.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bdiss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/disappointed.png"))); // NOI18N
        Bdiss.setBorder(null);
        Bdiss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Bdiss.setInheritsPopupMenu(true);
        Bdiss.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Bdiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdissActionPerformed(evt);
            }
        });
        jPanel4.add(Bdiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/shy.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FINAL/icons/excited (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("Hey! How are you feeling today?");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 317, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BhappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhappyActionPerformed
    HAPPY happy = new HAPPY();
    happy.setVisible(true);
        
        
    }//GEN-LAST:event_BhappyActionPerformed

    private void BjealousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BjealousActionPerformed
    JEALOUS jealous = new JEALOUS();
    jealous.setVisible(true);
    
    
    }//GEN-LAST:event_BjealousActionPerformed

    private void BtiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtiredActionPerformed
      TIRED tired = new TIRED();
      tired.setVisible(true);
    }//GEN-LAST:event_BtiredActionPerformed

    private void BdissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdissActionPerformed
       DISAPPOINTED disappointed = new DISAPPOINTED();
       disappointed.setVisible(true);
    }//GEN-LAST:event_BdissActionPerformed

    private void BangryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BangryActionPerformed
    ANGRY angry = new ANGRY();
    angry.setVisible(true);
    }//GEN-LAST:event_BangryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SHY shy = new SHY();
        shy.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BsadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsadActionPerformed
        SAD sad = new SAD();
        sad.setVisible(true);
    }//GEN-LAST:event_BsadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     EXCITED excited = new EXCITED();
     excited.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bangry;
    private javax.swing.JButton Bdiss;
    private javax.swing.JButton Bhappy;
    private javax.swing.JButton Bjealous;
    private javax.swing.JButton Bsad;
    private javax.swing.JButton Btired;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
